# Generated by Django 5.1.4 on 2025-01-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='modules',
            field=models.ManyToManyField(related_name='roles', through='user_permissions.RoleModule', to='user_permissions.module'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='user_permissions.RolePermission', to='user_permissions.permission'),
        ),
    ]
