# Generated by Django 5.1.4 on 2025-01-12 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_permissions', '0002_role_modules_role_permissions'),
    ]

    operations = [
    ]
