# Generated by Django 5.1.4 on 2025-01-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_permissions', '0002_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='permissions',
        ),
    ]
