# Generated by Django 5.1.4 on 2025-01-12 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_permissions', '0003_remove_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='modules',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user_permissions.role'),
        ),
    ]
