# Generated by Django 5.1.4 on 2025-01-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        help_text="WhatsApp number of the sender", max_length=255
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        help_text="WhatsApp number of the recipient", max_length=255
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("document", "Document"),
                        ],
                        default="text",
                        help_text="Type of the message",
                        max_length=50,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Text content of the message, if applicable",
                        null=True,
                    ),
                ),
                (
                    "media_url",
                    models.URLField(
                        blank=True,
                        help_text="URL of the media file, if applicable",
                        null=True,
                    ),
                ),
                (
                    "media_base64",
                    models.TextField(
                        blank=True,
                        help_text="Base64-encoded representation of the media",
                        null=True,
                    ),
                ),
                (
                    "media_mime_type",
                    models.CharField(
                        blank=True,
                        help_text="MIME type of the media, e.g., image/jpeg",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="Timestamp of when the message was received"
                    ),
                ),
                (
                    "is_forwarded_to_main_system",
                    models.BooleanField(
                        default=False,
                        help_text="Flag to track if the message was forwarded to the main system",
                    ),
                ),
            ],
        ),
    ]
