# Generated by Django 5.1.4 on 2025-01-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transcription", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transcription",
            old_name="transcript",
            new_name="model_transcription",
        ),
        migrations.AddField(
            model_name="transcription",
            name="true_transcription",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transcription",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="transcription",
            name="wer",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
