# Generated by Django 5.1.4 on 2025-01-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transcription",
            "0002_rename_transcript_transcription_model_transcription_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_id", models.CharField(max_length=20, unique=True)),
                ("date", models.DateTimeField()),
                ("talk_time", models.TimeField()),
                ("case_id", models.CharField(max_length=20)),
                ("narrative", models.TextField()),
                ("plan", models.TextField()),
                ("main_category", models.CharField(max_length=100)),
                ("sub_category", models.CharField(max_length=100)),
                ("gbv", models.BooleanField()),
            ],
        ),
    ]
