# Generated by Django 5.1.4 on 2025-01-29 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transcription", "0003_caserecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_id", models.CharField(max_length=50, unique=True)),
                ("audio_file", models.BinaryField()),
                ("feature_text", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ModelTranscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("predicted_text", models.TextField()),
                ("wer", models.FloatField()),
                ("model_version", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "audio_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transcription.audiofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Transcription",
        ),
        migrations.AlterField(
            model_name="caserecord",
            name="unique_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="transcription.audiofile",
            ),
        ),
        migrations.AddField(
            model_name="modeltranscription",
            name="model_version_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="transcription.modelversion",
            ),
        ),
    ]
