# Generated by Django 5.1.4 on 2025-01-23 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_audiofile_rawdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawdata",
            name="unique_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ai.audiofile"
            ),
        ),
    ]
