# Generated by Django 5.1.4 on 2025-01-29 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0004_alter_rawdata_unique_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="audiofile",
            name="feature_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audiofile",
            name="narrative",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ModelTranscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("predicted_text", models.TextField()),
                ("wer", models.FloatField()),
                ("model_version", models.CharField(max_length=50)),
                (
                    "unique_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ai.audiofile"
                    ),
                ),
                (
                    "model_version_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai.modelversion",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="RawData",
        ),
    ]
