# Generated by Django 5.1.4 on 2025-01-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0005_modelversion_audiofile_feature_text_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audiofile",
            old_name="audio_data",
            new_name="audio_file",
        ),
        migrations.RenameField(
            model_name="modeltranscription",
            old_name="unique_id",
            new_name="audio_id",
        ),
        migrations.RemoveField(
            model_name="audiofile",
            name="unique_id",
        ),
        migrations.AddField(
            model_name="audiofile",
            name="file_name",
            field=models.CharField(
                default="unknown_audio", max_length=255, unique=True
            ),
        ),
    ]
