# Generated by Django 5.1.4 on 2025-01-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0006_rename_audio_data_audiofile_audio_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modeltranscription",
            name="audio_id",
        ),
        migrations.RemoveField(
            model_name="modeltranscription",
            name="model_version_id",
        ),
        migrations.DeleteModel(
            name="AudioFile",
        ),
        migrations.DeleteModel(
            name="ModelTranscription",
        ),
        migrations.DeleteModel(
            name="ModelVersion",
        ),
    ]
