/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChildFriendlyCard: typeof import('./src/components/ChildFriendlyCard.vue')['default']
    DrawingBoard: typeof import('./src/components/DrawingBoard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HeroPage: typeof import('./src/components/HeroPage.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IMdiCaret: typeof import('~icons/mdi/caret')['default']
    IMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IMdiCons: typeof import('~icons/mdi/cons')['default']
    IMdiConsole: typeof import('~icons/mdi/console')['default']
    IMdiConsoleContr: typeof import('~icons/mdi/console-contr')['default']
    IMdiConsoleControl: typeof import('~icons/mdi/console-control')['default']
    IMdiConsoleController: typeof import('~icons/mdi/console-controller')['default']
    IMdiControllerClassi: typeof import('~icons/mdi/controller-classi')['default']
    IMdiControllerClassic: typeof import('~icons/mdi/controller-classic')['default']
    LayoutFile: typeof import('./src/components/LayoutFile.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
