/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChildFriendlyCard: typeof import('./src/components/ChildFriendlyCard.vue')['default']
    DrawingBoard: typeof import('./src/components/DrawingBoard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HeroPage: typeof import('./src/components/HeroPage.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IMdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    IMdiControllerClassic: typeof import('~icons/mdi/controller-classic')['default']
    IMdiControllerEmail: typeof import('~icons/mdi/controller-email')['default']
    IMdiControllerPhone: typeof import('~icons/mdi/controller-phone')['default']
    IMdiEmail: typeof import('~icons/mdi/email')['default']
    IMdiFace: typeof import('~icons/mdi/face')['default']
    IMdiFacebooj: typeof import('~icons/mdi/facebooj')['default']
    IMdiFacebook: typeof import('~icons/mdi/facebook')['default']
    IMdiInsta: typeof import('~icons/mdi/insta')['default']
    IMdiInstag: typeof import('~icons/mdi/instag')['default']
    IMdiInstagram: typeof import('~icons/mdi/instagram')['default']
    IMdiLink: typeof import('~icons/mdi/link')['default']
    IMdiLinkedin: typeof import('~icons/mdi/linkedin')['default']
    IMdiMa: typeof import('~icons/mdi/ma')['default']
    'IMdiMap-': typeof import('~icons/mdi/map-')['default']
    IMdiMapMarker: typeof import('~icons/mdi/map-marker')['default']
    IMdiPhone: typeof import('~icons/mdi/phone')['default']
    IMdiTw: typeof import('~icons/mdi/tw')['default']
    IMdiTwitter: typeof import('~icons/mdi/twitter')['default']
    IMdiYoutube: typeof import('~icons/mdi/youtube')['default']
    LayoutFile: typeof import('./src/components/LayoutFile.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
