# Generated by Django 5.1.4 on 2025-01-06 11:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note_text", models.TextField()),
                ("note_audio", models.BinaryField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ComplaintStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=50, null=True)),
                ("additional_info", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="audiofile",
            name="complaint",
        ),
        migrations.RemoveField(
            model_name="caseworkeraction",
            name="complaint",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="category",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="complaint",
        ),
        migrations.DeleteModel(
            name="Metric",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.RemoveField(
            model_name="translation",
            name="complaint",
        ),
        migrations.RemoveField(
            model_name="triagelog",
            name="complaint",
        ),
        migrations.RenameField(
            model_name="complaint",
            old_name="audio_url",
            new_name="complaint_text",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="id",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="language",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="severity",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="status",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="text",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="complaint",
            name="case_category",
            field=models.CharField(
                choices=[
                    ("ABUSE", "Abuse"),
                    ("HARASSMENT", "Harassment"),
                    ("FRAUD", "Fraud"),
                    ("NEGLECT", "Neglect"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="complaint_audio",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="complaint_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="reporter_nickname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="casenote",
            name="complaint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_notes",
                to="feedback.complaint",
            ),
        ),
        migrations.AddField(
            model_name="complaintstatus",
            name="complaint",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="feedback.complaint"
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="perpetrator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perpetrators",
                to="feedback.person",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="victim",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="victims",
                to="feedback.person",
            ),
        ),
        migrations.DeleteModel(
            name="AudioFile",
        ),
        migrations.DeleteModel(
            name="CaseworkerAction",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Feedback",
        ),
        migrations.DeleteModel(
            name="Translation",
        ),
        migrations.DeleteModel(
            name="TriageLog",
        ),
    ]
