# Generated by Django 5.1.4 on 2025-01-20 09:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0005_complaint_message_id_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="session_id",
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
