# Generated by Django 5.1.4 on 2025-01-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0006_alter_complaint_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="case_category",
            field=models.CharField(
                blank=True, default="Not Specified", max_length=255, null=True
            ),
        ),
    ]
