# Generated by Django 5.1.4 on 2025-01-29 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0006_alter_complaint_session_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="case_category",
        ),
    ]
