# Generated by Django 5.1.4 on 2025-01-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0007_alter_complaint_case_category"),
        ("feedback", "0007_remove_complaint_case_category"),
    ]

    operations = []
